version: '3'

services:
  victim:
    build: ./victim
    ports:
      - "5000:5000"
    container_name: cors-victim

  attacker:
    build: ./attacker
    ports:
      - "8000:80"
    container_name: cors-attacker